services:
  web:
    build: .
    command: /entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db

  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"